geektech/geektech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('geektech_admin/', admin.site.urls),
    path('geektech/', include('shopapp.urls')),
    path('user/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geektech/shopapp/urls.py
from django.urls import path, include

from .views import (ShopIndexView, ReviewsView, PromotionsView, DeliveryView,
                    ContactsView, CategoryDetailsView, cart_view, ProductDetailsView, cart_add, cart_delete, cart_decrease, order_create, FeedBackView)


app_name = 'shopapp'

urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),
    path('reviews/', ReviewsView.as_view(), name='reviews'),
    path('promotions/', PromotionsView.as_view(), name='promotions'),
    path('delivery/', DeliveryView.as_view(), name='delivery'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('category/<slug:slug>/', CategoryDetailsView.as_view(), name='category-detail'),
    path('product/<int:pk>/', ProductDetailsView.as_view(), name='product-details'),
    path('cart/', cart_view, name='cart'),
    path('cart/cart-add/<int:product_id>/', cart_add, name='cart-add'),
    path('cart/cart-delete/<int:product_id>/', cart_delete, name='cart-delete'),
    path('cart/cart-decrease/<int:product_id>/', cart_decrease, name='cart-decrease'),
    path('order/create/', order_create, name='order-create'),
    path('reviews/feedback', FeedBackView.as_view(), name='feedback'),

]

geektech/users/urls.py
from django.urls import path
from .views import profile_view, RegisterView

app_name = 'users'

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('register/', RegisterView.as_view(), name='register')
]

geektech/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class ProductImage(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='product_images')
    image = models.ImageField(upload_to='products/images/')

    def __str__(self):
        return f"Image for {self.product.product_name}"


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    product_name = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=80)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    images = models.ManyToManyField(ProductImage, blank=True, related_name='products')
    preview = models.ImageField(upload_to='products/previews/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    discount = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    stock_quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")

    def __str__(self):
        return f"{self.product_name} ({self.manufacturer})"


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.username}, продукт {self.product.product_name}'


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    created_at = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    products = models.ManyToManyField('Product', through='OrderItem')

    def update_total_price(self):
        total = 0
        for item in self.items.all():
            total += item.quantity * item.price
        self.total_price = total
        self.save()

    def __str__(self):
        return f"Заказ №{self.id} - {self.user.username}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)


class Feedback(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    text = models.TextField(max_length=2000)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Автор: {self.author.username} {self.title}'


class Promotion(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField(max_length=2000)

    def __str__(self):
        return f'{self.title}'


class Delivery(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField(max_length=2000)

    def __str__(self):
        return f'{self.title}'


class Contact(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField(max_length=2000)

    def __str__(self):
        return f'{self.title}'

geektech/shopapp/views.py
import slug
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.context_processors import request
from django.views import View
from django.views.generic import ListView, DetailView
from django.db import models

from .models import Product, Category, Cart, Feedback, Promotion, Delivery, Contact, Order, OrderItem


# Create your views here.

class ShopIndexView(View):
    def get(self, request):
        products = Product.objects.all()
        categories = Category.objects.all()
        return render(request, 'geektech.html', {'products': products, 'categories': categories})


class ReviewsView(View):
    def get(self, request: HttpRequest):
        feedbacks = Feedback.objects.all().order_by('-created_timestamp')
        return render(request, 'reviews.html', {'feedbacks': feedbacks})


class PromotionsView(View):
    def get(self, request: HttpRequest):
        promotions = Promotion.objects.all()
        return render(request, 'promotions.html', {'promotions': promotions})


class DeliveryView(View):
    def get(self, request: HttpRequest):
        deliveries = Delivery.objects.all()
        return render(request, 'delivery.html', {'deliveries': deliveries})


class ContactsView(View):
    def get(self, request: HttpRequest):
        contacts = Contact.objects.all()
        return render(request, 'contacts.html', {'contacts': contacts})


class ProductListView(View):
    model = Product
    template_name = 'products/product_list.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class CategoryDetailsView(ListView):
    template_name = 'category.html'
    context_object_name = 'products'

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return Product.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        context['categories'] = Category.objects.all()
        return context


class CategoryPreviewView(View):
    def get(self, request, slug):
        category = Category.objects.get(slug=slug)
        return render(request, 'category.html', {'category': category})


class ProductDetailsView(DetailView):
    model = Product
    template_name = 'product-details.html'
    context_object_name = 'product'


@login_required
def cart_view(request: HttpRequest):
    cart_items = Cart.objects.filter(user=request.user)
    total_price = sum(item.product.price * item.quantity for item in cart_items)
    for item in cart_items:
        item.total_price = item.quantity * item.product.price
    return render(request, 'cart.html', {'cart_items': cart_items, 'total_price': total_price})


@login_required
def cart_add(request: HttpRequest, product_id: int):
    current_page = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=product_id)
    cart = Cart.objects.filter(user=request.user, product=product)
    if not cart.exists():
        Cart.objects.create(user=request.user, product=product, quantity=1)
        return HttpResponseRedirect(current_page)
    else:
        cart = cart.first()
        cart.quantity += 1
        cart.save()
        return HttpResponseRedirect(current_page)


def cart_delete(request: HttpRequest, product_id: int):
    cart = Cart.objects.get(id=product_id)
    cart.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def cart_decrease(request, product_id: int):
    cart_item = Cart.objects.get(product__id=product_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.update_total_price()
    return render(request, 'order_detail.html', {'order': order})


def order_create(request):
    if request.method == 'POST':
        cart_items = Cart.objects.filter(user=request.user)
        order = Order.objects.create(user=request.user)
        total_price = 0

        for item in cart_items:
            if item.product.stock_quantity >= item.quantity:
                order_item = OrderItem.objects.create(
                    order=order,
                    product=item.product,
                    quantity=item.quantity,
                    price=item.product.price
                )
                item.product.stock_quantity -= item.quantity
                item.product.save()
                total_price += item.product.price * item.quantity
            else:
                return render(request, 'base.html', {
                    'message': f'Недостаточно товара {item.product.product_name} на складе.'
                })

        order.total_price = total_price
        order.save()
        cart_items.delete()

        return redirect('users:profile')


class FeedBackView(View):
    def get(self, request: HttpRequest):
        feedbacks = Feedback.objects.all().order_by('-created_timestamp')
        return render(request, 'feedback.html')

    def post(self, request: HttpRequest):
        text = request.POST.get('text', '')
        title = request.POST.get('title', '')
        if not request.user.is_authenticated:
            return HttpResponse("Вы должны быть авторизованы, чтобы оставить отзыв", status=403)

        if text and title:
            Feedback.objects.create(
                title=title,
                text=text,
                author=request.user
            )
        return redirect('shopapp:reviews')

geektech/shopapp/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}GeekTech{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block additional_styles %}
    {% endblock %}
</head>
<body>
    <header>
        <div class="menu">
            <a href="{% url 'shopapp:index' %}">Главная</a>
            <a href="{% url 'shopapp:reviews' %}">Отзывы</a>
            <a href="{% url 'shopapp:promotions' %}">Акции</a>
            <a href="{% url 'shopapp:delivery' %}">Доставка</a>
            <a href="{% url 'shopapp:contacts' %}">Контакты</a>
        </div>
        <div class="log-reg-menu">
            {% if user.is_authenticated %}
                <a href="{% url 'users:profile' %}">Привет, {{ user.username }}</a>
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{% url 'shopapp:index' %}">
                    <button type="submit" class="btn-logout">Выйти</button>
                </form>
            {% else %}
                <a href="{% url 'users:profile' %}">Войти</a>
                <a href="{% url 'users:register' %}">Регистрация</a>
            {% endif %}
        </div>
    </header>

    <main>
        {% block main %}
        {% if message %}
            <div class="error-message">
                <p>{{ message }}</p>
            </div>
        {% endif %}
        {% endblock %}
    </main>

    <footer>
        <div class="footer-content">
            <span>Обратная связь | Телефон: 8 (900) 353-03-35 | Email: geektech@gmail.com | <a href="{% url 'shopapp:cart' %}">Корзина</a></span>
        </div>
    </footer>
</body>
</html>

geektech/shopapp/templates/cart.html
{% extends 'base.html' %}

{% block title %}Корзина - GeekTech{% endblock %}
{% block additional_styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
{% endblock %}
{% block main %}
<div class="cart-container">
    <div>Привет, {{ user.username }}!</div>
    {% if not cart_items %}
        <p class="cart-empty">Твоя корзина пуста</p>
    {% else %}
        {% for item in cart_items %}
            <div class="cart-item">
                <div>
                    <p>Название: {{ item.product.product_name }}</p>
                    <p>Цена за штуку: {{ item.product.price }} ₽</p>
                    <p>Количество: {{ item.quantity }}</p>
                    <p>Итого: {{ item.total_price }} ₽</p>
                </div>
                <div class="cart-item-actions">
                    <a href="{% url 'shopapp:cart-decrease' item.product.id %}">-</a>
                    <a href="{% url 'shopapp:cart-add' item.product.id %}">+</a>
                    <a href="{% url 'shopapp:cart-delete' item.id %}">Очистить</a>
                </div>
            </div>
        {% endfor %}
        <div class="cart-total">
            <p>Итого: {{ total_price }} ₽</p>
        </div>
        <form id="order-form" method="POST" action="{% url 'shopapp:order-create' %}">
            {% csrf_token %}
            <button type="submit">Купить</button>
        </form>
    {% endif %}
</div>
{% endblock %}

geektech/shopapp/templates/category.html
{% extends 'base.html' %}

{% block title %}{{ category.name }} - GeekTech{% endblock %}
{% block additional_styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
{% endblock %}
{% block main %}
 <main class="main-content">
        <h2 class="center-title">Товары категории "{{ category.name }}"</h2>
        <ul class="product-list">
            {% for product in products %}
                <li>
                    {% if product.preview %}
                        <img src="{{ product.preview.url }}" alt="{{ product.product_name }}">
                    {% else %}
                        <img src="{% static 'images/no-image.png' %}" alt="No image available">
                    {% endif %}
                    <a href="{% url 'shopapp:product-details' product.pk %}">
                        <h3>{{ product.product_name }}</h3>
                    </a>
                    <p>Цена: {{ product.price }} ₽</p>
                    <p>Категория: {{ product.category.name }}</p>
                </li>
            {% endfor %}
        </ul>
    </main>
{% endblock %}

geektech/shopapp/templates/contacts.html
{% extends 'base.html' %}

{% block title %}Контакты - GeekTech{% endblock %}

{% block additional_styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/contacts.css' %}">
{% endblock %}

{% block main %}
    <h1>Наши контакты</h1>
    <div class="container">
        {% for contact in contacts %}
            <div class="contact-item">
                <h2>{{ contact.title }}</h2>
                <p>{{ contact.text }}</p>
            </div>
        {% empty %}
            <div class="contact-item">
                <h2>Информация недоступна</h2>
                <p>На данный момент контакты отсутствуют. Пожалуйста, свяжитесь с нами позже.</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

geektech/shopapp/templates/delivery.html
{% extends 'base.html' %}

{% block title %}Доставка - GeekTech{% endblock %}

{% block additional_styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/delivery.css' %}">
{% endblock %}

{% block main %}
    <h1>Информация о доставке</h1>
    {% for delivery in deliveries %}
        <div class="delivery-item">
            <h2>{{ delivery.title }}</h2>
            <p>{{ delivery.text }}</p>
        </div>
    {% empty %}
        <div class="delivery-item">
            <h2>Информация недоступна</h2>
            <p>На данный момент информация о доставке отсутствует.</p>
        </div>
    {% endfor %}
{% endblock %}


geektech/shopapp/templates/feedback.html
{% extends 'base.html' %}

{% block title %}Оставить отзыв - GeekTech{% endblock %}
{% block additional_styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/feedback.css' %}">
{% endblock %}

{% block main %}
<div class="feedback-page">
    <form class="feedback-card" action="{% url 'shopapp:feedback' %}" method="POST">
        {% csrf_token %}
        <h2 class="feedback-title">Оставьте свой отзыв</h2>
        <p class="feedback-subtitle">Ваше мнение помогает нам становиться лучше</p>
        <div class="feedback-input-group">
            <input type="text" name="title" placeholder="Заголовок отзыва" class="feedback-input" required>
        </div>
        <div class="feedback-input-group">
            <textarea name="text" rows="5" placeholder="Напишите ваш отзыв здесь..." class="feedback-textarea" required></textarea>
        </div>
        <button type="submit" class="feedback-btn">Отправить отзыв</button>
    </form>
</div>
{% endblock %}

geektech/shopapp/templates/geektech.html
{% extends 'base.html' %}

{% block title %}GeekTech{% endblock %}

{% block additional_styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/geektech.css' %}">
{% endblock %}

{% block main %}
    <section>
        <div class="catalog-menu">
            <h1>Категории товаров</h1>
            <ul class="catalog-menu-items">
                {% for category in categories %}
                    <li><a href="{% url 'shopapp:category-detail' slug=category.slug %}">{{ category.name }}</a></li>
                {% empty %}
                    <li>Нет доступных категорий.</li>
                {% endfor %}
            </ul>
        </div>

        <div class="main-content">
            <h2 class="center-title">Все товары</h2>
            {% if products %}
            <ul class="product-list">
                {% for product in products %}
                    <li>
                        {% if product.preview %}
                            <img src="{{ product.preview.url }}" alt="{{ product.product_name }}">
                        {% else %}
                            <img src="{% static 'images/no-image.png' %}" alt="No image available">
                        {% endif %}
                        <a href="{% url 'shopapp:product-details' product.pk %}">
                        <h3>{{ product.product_name }}</h3>
                        </a>
                        <p>Цена: {{ product.price }} ₽</p>
                        <p>Категория: {{ product.category.name }}</p>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
            <p class="center-title">Нет доступных товаров.</p>
            {% endif %}
        </div>
    </section>
{% endblock %}


geektech/shopapp/templates/product-details.html
{% extends 'base.html' %}

{% block title %}{{ product.product_name }} - GeekTech{% endblock %}
{% block additional_styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/product-details.css' %}">
{% endblock %}
{% block main %}
<div class="product-detail">
    <h1 class="product-title">{{ product.product_name }}</h1>
    <p class="manufacturer">Производитель: <span>{{ product.manufacturer }}</span></p>
    <p class="price">Цена: <span>{{ product.price }} ₽</span></p>
    {% if product.discount %}
    <p class="discount">Скидка: <span>{{ product.discount }}%</span></p>
    {% else %}
    <p class="description">{{ product.description }}</p>
    {% endif %}
    {% if product.preview %}
    <div class="product-preview">
        <img src="{{ product.preview.url }}" alt="{{ product.product_name }} preview" class="preview-image"
             onclick="openModal('{{ product.preview.url }}')">
    </div>
    {% endif %}
    <div class="product-images">
        {% for image in product.images.all %}
        <div class="product-image">
            <img src="{{ image.image.url }}" alt="Изображение товара {{ product.product_name }}" class="product-img"
                 onclick="openModal('{{ image.image.url }}')">
        </div>
        {% endfor %}
    </div>

    <div class="product-info">
        <div class="product-stock">
            <p>Количество на складе: <span>{{ product.stock_quantity }}</span></p>
        </div>
    </div>
    <a href="{% url 'shopapp:cart-add' product.id %}">
        <button class="add-to-cart-btn">Добавить в корзину</button>
    </a>
</div>

{% endblock %}

geektech/shopapp/templates/promotions.html
{% extends 'base.html' %}

{% block title %}Акции - GeekTech{% endblock %}
{% block additional_styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/promotions.css' %}">
{% endblock %}
{% block main %}
        <h1>Акции и специальные предложения</h1>
        {% for promotion in promotions %}
        <div class="promotion-item">
            <h2>{{ promotion.title }}</h2>
            <p>{{ promotion.text }}</p>
            {% endfor %}
        </div>
{% endblock %}

geektech/shopapp/templates/reviews.html
{% extends 'base.html' %}

{% block title %}Отзывы - GeekTech{% endblock %}

{% block additional_styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/reviews.css' %}">
{% endblock %}

{% block main %}
<h1>Отзывы наших клиентов</h1>

<div class="feedbacks-container">
    {% for review in feedbacks %}
        <div class="feedback">
            <p><strong>{{ review.title }}</strong></p>
            <p>{{ review.text }}</p>
            <p class="name">Автор: {{ review.author.username }}</p>
            <p class="date">{{ review.created_timestamp|date:"d.m.Y H:i" }}</p>
        </div>
    {% empty %}
        <div class="no-feedback">
            <p>Пока нет отзывов. Будьте первым, кто оставит отзыв!</p>
        </div>
    {% endfor %}
</div>

{% endblock %}